export const projects = [
  {
    title: "Jobster",
    description:
      "Jobster; A MERN stack application that puts jobs into a job queue to execute. Manage and ensures that the job applications are declined, pending or interviewed in appropriate order. It can add, edit, remove according to the author of the job. Has a sorting algorithm and authentication mechanism",
    // note: "THIS IS UNDER MAINTERNANCE BECAUSE I'VE PLAN TO DO THIS AS FULL FLEDGE APPLICATION USING NODE.JS/EXPRESS AS BACKEND AND MONGODB FOR DATABASE...",
    image: "/assets/mockups/jobster-app.png",
    tags: ["MongoDB", "Express", "React", "Css-in-JS"],
    source: "prohibited",
    // visit: "/pages/404.tsx",
    // source: "https://github.com/tanaliga100/jobsterApp",
    visit: "https://jobster-9foc.onrender.com/landing",
    id: 17,
  },
  // {
  //   title: "blastAdmin",
  //   description:
  //     "blastAdmin; a full blown admin site application built with React.js/Typescript. A dashboard management software that is designed to monitor the health of a business, department or specific process by visually tracking, analyzing and displaying key performance indicators (KPI) metrics and key data points using different graphical options.",
  //   // note: "THIS IS UNDER MAINTERNANCE BECAUSE I'VE PLAN TO DO THIS AS FULL FLEDGE APPLICATION USING NODE.JS/EXPRESS AS BACKEND AND MONGODB FOR DATABASE...",
  //   image: "/assets/mockups/react-admin.png",
  //   tags: ["React", "Typescript", "MUI"],
  //   // source: "no-entry",
  //   // visit: "/pages/404.tsx",
  //   source: "https://github.com/tanaliga100/react-ts-dashboard",
  //   visit: "https://react-ts-admin-nine.vercel.app/",
  //   id: 18,
  // },
  {
    title: "Lazamo",
    description:
      "Lazamo; a full fledge e-commerce app built with React.js and Express as a backend with Typescript. Its an ordering app inspired from lazada.I used Redux as a state management for this project with a combinations of react-redux hooks [useSelector & useDispatch] ",
    note: "THIS IS UNDER MAINTERNANCE AS BACKEND WORK IS ONGOING...",
    image: "/assets/mockups/store.png",
    tags: ["Express", "React", "Node", "Typescript"],
    source: "/pages/404.tsx",
    // visit: "/pages/404.tsx",
    // source: "https://github.com/tanaliga100/react-store/",
    visit: "https://lazamo.vercel.app/",
    id: 4,
  },
  // {
  //   title: "socioLive",
  //   description:
  //     "socioLive; a simple social media app built with React.js & MUI for FrontEnd and Express as a backend with Typescript. This app is inspired from from facebook but not the whole functionality it serves. I used RTK as a state management libary for this project",
  //   note: "THIS IS UNDER MAINTERNANCE BECAUSE I'VE PLAN TO DO THIS AS FULL FLEDGE APPLICATION USING NODE.JS/EXPRESS AS BACKEND AND MONGODB FOR DATABASE...",
  //   image: "/assets/mockups/socio.png",
  //   tags: ["Express", "React", "MUI", "Typescript"],
  //   // source: "no-entry",
  //   // visit: "/pages/404.tsx",
  //   source: "/pages/404.tsx",
  //   visit: "https://socio-live.vercel.app/",
  //   id: 5,
  // },

  // {
  //   title: "Netflox",
  //   description:
  //     "Netflox; a full fledge entertainment app built with Next.js and Firebase as a backend. Its basically a movie app inspired from netflix.",
  //   image: "/assets/mockups/netflix.png",
  //   tags: ["Firebase", "Next.js", "Typescript", "Tailwind"],
  //   // source: "https://github.com/tanaliga100/redux-core-with-hooks",
  //   // source: "no-entry",
  //   // visit: "/pages/404.tsx",
  //   source: "https://github.com/tanaliga100/netflox",
  //   visit: "https://netflox-beryl.vercel.app/",
  //   id: 16,
  // },
  {
    title: "Food Order App",
    description:
      "Using React, Node.js, and Firebase as backend. I learn how to build a Full Stack  Application - from start to finish.Its an ordering app that allows users to takes an order depending on what they wanted.I used contextAPI as a state management for this project which helps to centralize the store/data with a combinations of react-hooks",
    image: "/assets/mockups/react-meals.png",
    tags: ["Firebase", "React", "Node", "CSS Modules"],
    source: "prohibited",
    // visit: "/pages/404.tsx",
    // source: "https://github.com/tanaliga100/react-meals/",
    visit: "https://react-meals-topaz.vercel.app/",
    id: 15,
  },
  // {
  //   title: "D&D",
  //   description:
  //     "A drag and drop project purely built with Typescript in an object-oriented manner. Can drag from active to finished && vice-versa. I've used webpack bundler for this project",
  //   image: "/assets/mockups/d&d.png",
  //   tags: ["Typescript", "Node", "TailwindCss"],
  //   // source: "no-entry",
  //   // visit: "/pages/404.tsx",
  //   source: "https://github.com/tanaliga100/d_and_d",
  //   visit: "https://d-and-d-two.vercel.app/",
  //   id: 19,
  // },
  // {
  //   title: "Expense - Tracker",
  //   description:
  //     "This app focused on expenditures. It keeps a daily record of your expenses by tracking the expenses per year,  and other outgoing expenses. I used a dummy data array for this to sort.  Nonetheless it shows the capability of tracking an expenses.",
  //   image: "/assets/mockups/expense-tracker.png",
  //   tags: ["React", "Css Modules"],
  //   // source: "no-entry",
  //   // visit: "/pages/404.tsx",
  //   source: "https://github.com/tanaliga100/react-expense-tracker/",
  //   visit: "https://react-expense-tracker-steel.vercel.app/",
  //   id: 14,
  // },
  {
    title: "Quotivate ",
    description:
      "This app lets you create a quotes with an author tag. Also you can put a comment under for whatever reason you might want to. I used firebase as a backend database which let data persist not just in the UI. Also I used the vite module bundler here for rapid instance of the projects.",
    image: "/assets/mockups/great-quotes.png",
    tags: ["React", "Css Modules", "Firebase", "Vite"],
    source: "prohibited",
    // visit: "/pages/404.tsx",
    // source: "https://github.com/tanaliga100/react-quotes",
    visit: "https://react-quotes-blond.vercel.app/quotes",
    id: 13,
  },
  // {
  //   title: "bookStorey",
  //   description:
  //     "A simulation of simple e-commerce site with firebase as a backend.  I learned a solid foundation of reduxjs/toolkit by building this app. I used a combinations of useSelector and useDispatch from the react-redux library. This is an experimental app for me and my first ever React project",
  //   image: "/assets/mockups/rtk-cart.png",
  //   tags: ["React", "Firebase", "MUI", "RTK"],
  //   // source: "no-entry",
  //   // visit: "/pages/404.tsx",
  //   source: "https://github.com/tanaliga100/bookStorey",
  //   visit: "https://book-storey.vercel.app/",
  //   id: 12,
  // },
  //   {
  //     title: "Landing Page",
  //     description:
  //       "This is a code-along project so nothing special. What I personally gain about building this app is how to use webpack from scratch. We all know, most of the technologies out there are already running through webpack. Most of all javascript libraries/frameworks to name a few. So in conclusion this experimental app helps me to understand what webpack is and how it works under the hood",
  //     image: "/assets/mockups/landing-page.png",
  //     tags: ["Tailwind", "VanillaJS", "Webpack"],
  //     source: "https://github.com/tanaliga100/tailwind-landing-page",
  //     visit: "https://tailwind-landing-page-kappa.vercel.app/",
  //     id: 11,
  //   },
  {
    title: "DoAny App",
    description:
      "This app makes me broaden my skill on Javascript. It serves as the summary of my Javascript knowledge. Just javascript no frameworks. I showcase the basic functionality of CRUD in this app.",
    image: "/assets/mockups/todo-app.png",
    tags: ["Vanilla JS", "Vanilla Css"],
    source: "prohibited",
    // visit: "/pages/404.tsx",
    // source: "https://github.com/tanaliga100/todo-app",
    visit: "https://todo-app-kohl-mu.vercel.app/",
    id: 10,
  },
  //   {
  //     title: "Covid19 - Tracker",
  //     description:
  //       "This app introduce me to learn RESTful API. How it works and be done. I use the public API for this app. This doesn't do alot of functionalities as compared to others but I gain more knowledge by building this app. This was an experimental app for me that measures my creativity.",
  //     image: "/assets/mockups/covid-tracker.png",
  //     tags: ["React", "Tailwind Css"],
  //     source: "no-entry",
  //     visit: "/pages/404.tsx",
  //     id: 9,
  //   },
  //   {
  //     title: "Redux - Cart",
  //     description:
  //       "This app became the summary of my studies in Redux. A state-management solution for react. I worked with the redux-core principles. Using the connect functions,  mapStateToProps and mapDispatchToProps subsequently to spread the state across the app without the need of hooks.",
  //     image: "/assets/mockups/redux-cart.png",
  //     tags: ["React", "MUI", "Redux"],
  //     // source: "no-entry",
  //     // visit: "/pages/404.tsx",
  //     source: "https://github.com/tanaliga100/redux-core/",
  //     visit: "https://redux-cart-delta.vercel.app/",
  //     id: 8,
  //   },
  //   {
  //     title: "Task-Lister App",
  //     description:
  //       "By building this App I learned many advanced React topics such as routing in depth but on top of that is I learned how to use React Hooks, which makes it easier to manage and much modern.",
  //     image: "/assets/mockups/task-lister.png",
  //     tags: ["React", "Hooks", "Bootstrap"],
  //     // source: "no-entry",
  //     // visit: "/pages/404.tsx",
  //     source: "https://github.com/tanaliga100/react-101/",
  //     visit: "https://react-task-tracker-rho.vercel.app/",
  //     id: 7,
  //   },
  //   {
  //     title: "EveryDay-Note",
  //     description:
  //       "This app is a bit similar to a todo app I've built. So nothing special. What I've personally learn about building this app is code refactoring or code splitting.",
  //     image: "/assets/mockups/note-taking-app.png",
  //     tags: ["Vanilla JS", "Vanilla Css"],
  //     // source: "no-entry",
  //     // visit: "/pages/404.tsx",
  //     source: "https://github.com/tanaliga100/note-taking-app",
  //     visit: "https://note-taking-app-orcin.vercel.app/index.html",
  //     id: 6,
  //   },
  //   {
  //     title: "Hangman Game",
  //     description:
  //       "This is a simple game app which let you guess the random word from an api. It counts every single stroke the user is guessing and gives a feedback how many attempt are left. Also whenever the user is guessing the correct letter will pop-up. This is an experimental app for me which measures my logical thinking.",
  //     image: "/assets/mockups/guess-the-word.png",
  //     tags: ["Vanilla JS", "Vanilla Css"],
  //     // source: "no-entry",
  //     // visit: "/pages/404.tsx",
  //     source: "https://github.com/tanaliga100/hangman/",
  //     visit: "https://hangman-lac.vercel.app/",
  //     id: 5,
  //   },
  // {
  //   title: "Finance - Logger",
  //   description:
  //     "This app is built with pure Typescript in an Object-Oriented manner. I've never done that before. So as a refresher I built this simple finance logger app.",
  //   note: "THIS PROJECT IS UNDER MAINTERNANCE BECAUSE I'VE PLAN TO DO THIS AS FULL FLEDGE APPLICATION USING NODE.JS/EXPRESS AS BACKEND AND MONGODB FOR DATABASE...",
  //   image: "/assets/mockups/finance-logger.png",
  //   tags: ["Typescript", "Webpack", "Tailwind", "JS"],
  //   // source: "no-entry",
  //   visit: "/pages/404.tsx",
  //   source: "https://github.com/tanaliga100/finance-logger/",
  //   // visit: "https://finance-logger-gamma.vercel.app/",
  //   id: 3,
  // },

  //   {
  //     title: "React - Authentication",
  //     description:
  //       "This app sends the access token to the local storage which act as a backend server and perform a fetching with each subsequent request every time the user creates a new account or login either. I used the RTK for managing the state",
  //     image: "/assets/mockups/react-auth.png",
  //     tags: ["React", "Css Modules", "React-Redux", "RTK"],
  //     // source: "no-entry",
  //     // visit: "/pages/404.tsx",
  //     source: "https://github.com/tanaliga100/react-authentication",
  //     visit: "https://react-authentication-ochre.vercel.app/",
  //     id: 2,
  //   },
  //   {
  //     title: "jordantanaliga100 | E-Portfolio",
  //     description:
  //       "This is an online representation of my work. What I have created, as well as my skills, and experiences.",
  //     image: "/assets/mockups/portfolio-cp.png",
  //     tags: ["React", "Tailwind", "NextJs", "Typescript"],
  //     id: 1,
  //   },
];
export const TimeLineData = [
  {
    id: 0,
    year: 2013,
    text: "In 2013, Jordan began his journey as a CCE student at STI College-Munoz. He's so excited to learn everything about computers and technology, and over the next two years, he worked hard to gain a solid foundation in the field.",
  },
  {
    id: 1,
    year: 2015,
    text: "After completing a two-year course, Jordan decided to pursue a Bachelor of Science in Information Technology at the same school. The next few years he spent studying hard and learning all he could about technology and coding.  ",
  },
  {
    id: 2,
    year: 2018,
    text: "In 2018, Jordan decided to takes learning to the next level and started to learn coding by himself. Applied for online courses and ventured into the world of JavaScript. Jordan specialized React.js framework as a main stack and spent free time learning from open-source tutorials on the internet",
  },
  {
    id: 3,
    year: 2021,
    text: "Finally, in October 2021, Jordan graduated from college with a Bachelor of Science in Information Technology...",
  },
];
